### PR TITLE
Dev hack feb 2023

### PR DESCRIPTION
**Pull request by mzaiss**
solves issues 
#30 
#32
#33 
#34 
#36 
#39 

i compared simulation outcome already, all fine, minor difference as some M0 normalizations were changed form -1500 ppm to -300ppm  as -1500 ppm cause troubles at some scanners.

### CODE REVIEW

**Comment by schuenke** [comment]
I am currently refactoring the python files and will release a new version of the bmctool, which is used to adjust the naming to the MATLAB naming etc.,  in parallel. Thus it might take another two days to finish everything.

**Comment by schuenke** [comment]
Please recreate the seq-file for **APTw_3T_003_...** using the adjusted *m file. I hope I fixed a bug but have no MATLAB to test it.

**Comment by schuenke** [comment]
Please recreate the seq-file for **DGE_7T_001...** using the adjusted *m file. I fixed a naming but have no MATLAB.

**Review by schuenke — CHANGES_REQUESTED** [review]
The *.seq-files for the following cases need to be recreated:

- APTw_3T_000 (changed B1cwpe to B1rms)
- APTw_3T_003 (variable names instead of values were written to definitions)
- DGE_7T_001 (changed B1peak to B1pa)

Issue #41 should be solved and the files should be adjusted accordingly before merge

**Comment by mzaiss** [comment]
Ok, I recreated requested files.

However, for the DGE_7T really the peak B1 was meant and given in the literature.

the pulse shape was explicitly adjusted for the beak B1 here: 

satPulse      = mr.makeSincPulse(fa_sat, 'Duration', defs.tp, 'system', seq.sys,'timeBwProduct', 2,'apodization', 0.15); % philips-like sinc
satPulse.signal = (satPulse.signal./max(satPulse.signal)).*defs.B1peak*gamma_hz; 


i hope you did the same in pypulseq.

otherwise free to merge!

**Review by schuenke — APPROVED** [review]

**Comment by schuenke** [comment]
I renamed B1pa to B1peak in DGE_7T_001 and yes, I use the same scaling in python:

```python
sat_pulse.signal = (sat_pulse.signal / np.max(sat_pulse.signal)) * defs["b1peak"] * GAMMA_HZ
```

**Pull request merged**
