### PR TITLE
adjust to pypulseq 1.3.1 and new BMCTool version

### PR DESCRIPTION
**Pull request by schuenke**
adjustments to new versions of the python packages **pypulseq** (version >=1.3.1) and **bmctool** (version >= 0.3.1)

### CODE REVIEW

**Comment by kherz** [comment]
Can you update the BMCTool as well? Right now I get errors due to pypulseq1.2.post4 when I test the new function

**Comment by schuenke** [comment]
Sorry, wanted to publish the BMCTool release just after opening the PR but than something else came up. Now, [BMCTool 0.3.1](org/project/BMCTool/0.3.1/) should be available. Just use `pip install --upgrade bmctool` to upgrade to the latest version.

**Comment by schuenke** [comment]
Just realized that the bug fixes in pypulseq 1.3.1 are only available in the dev branch atm. To force the installation of the dev branch just use

 `pip install --ignore-installed git+https://github.com/imr-framework/pypulseq.git@dev`

As discussed with @kherz we will leave the PR open until the bug fixes in pypulseq are released.

**Comment by schuenke** [comment]
pypulseq 1.3.1post1 was released this week and after some tests I released [BMCTool 0.3.1post1](https://pypi.org/project/BMCTool/0.3.1.post1/) today. 

```pip install --upgrade bmctool```

should update both, BMCTool and pypulseq to the latest versions.

**Comment by kherz** [comment]
Works, I merge the PR

**Pull request merged**
