### PR TITLE
removed non-native yaml types

### PR DESCRIPTION
**Pull request by kherz**
see issue #16

### CODE REVIEW

**Comment by mzaiss** [comment]
Oh. This is a major change of the standard going from R to T.
This will kill all downward compatibility.
Is this really wanted?
Cant we just add the t1 as a comment?

**Comment by schuenke** [comment]
As far as I know, we implemented a compatibility for both, T1/T2 AND R1/R2, no?! Thus, changing the default values in the yaml files should not affect the compatibility.

**Comment by kherz** [comment]
The matlab functions can handle both, r1 and t1 as input. So no problem with compatibility. 
We can also stick with r1 and r2 and just invert the t1 and t2 values in this pr, but without using fractions again

**Review by schuenke — APPROVED** [review]
- maybe mention compatibility for R and T values in README and in the comment/header sections in the YAML files

**Comment by kherz** [comment]
I added some readme information.
btw.: what happened to this branch: https://github.com/kherz/pulseq-cest-library/tree/readme @schuenke ? Still active?

**Comment by mzaiss** [comment]
Ok!

Patrick Schuenke ***@***.***> schrieb am Mo., 16. Aug. 2021,
16:25:

**Comment by schuenke** [comment]
> 
> 
> I added some readme information.
> btw.: what happened to this branch: https://github.com/kherz/pulseq-cest-library/tree/readme @schuenke ? Still active?

you included (some of) the changes of the "readme" branch in the current branch, no?! Thus I am fine if we delete the "readme" branch without merging it.

**Pull request merged**
